version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: tiago
      POSTGRES_PASSWORD: tiago123
      POSTGRES_DB: python_crud
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tiago -d python_crud"]
      interval: 3s
      timeout: 3s
      retries: 5

  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy 
    environment:
      - DATABASE_URL=postgresql://tiago:tiago123@db:5432/python_crud
      - PYTHONPATH=/code

volumes:
  postgres_data:
