[pytest]
# Configuração para ignorar avisos visuais do Pydantic
filterwarnings =
    ignore::DeprecationWarning:pydantic.*

# Adiciona argumentos padrão do comando pytest
# --cov=app: Mede a cobertura da pasta app/
# --cov-report=term-missing: Mostra a porcentagem e aponta no terminal quais linhas exatas não foram testadas
addopts = -v --cov=app --cov-report=term-missing
